---
fixtures:
  repositories:
    stdlib:
      ref: "v6.0.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    vision_docker:
      ref: "production"
      repo: "https://github.com/vision-it/vision-docker"
  symlinks:
    vision_traefik: '#{source_dir}'
